name: Backfill covers (one-off)

on:
  workflow_dispatch:

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backfill
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          OVERWRITE: "false"
        run: |
          source .venv/bin/activate
          python backfill_covers.py
